
-- Explore all countries our customers come from
select DISTINCT country from gold.dim_customers

--Explore All Categories "The major Divisions"
select DISTINCT category,subcategory,product_name from gold.dim_product
order by 1,2,3

--Find the date of first and last order
--How many years of sales are available
select 
MIN(order_date) First_order_date,
MAX(order_date) last_order_date,
DATEDIFF(YEAR,MIN(order_date),MAX(order_date)) AS order_range_years
from gold.fact_sales

-- Find the total_sales
select sum(sales_amount) as total_sales from gold.fact_sales
-- Find how many items are sold
select sum(quantity) as total_quantity from gold.fact_sales
-- Find the average selling price
select avg(price) as avg_price from gold.fact_sales
-- Find the Total number of Orders
select count(order_number) as total_orders from gold.fact_sales
select count(distinct order_number) as total_orders from gold.fact_sales
-- Find the total number of products
select count(product_key) as total_products from gold.dim_product
-- Find the total number of customers
select count(customer_key) as total_customers from gold.dim_customers
-- Find the total number of customers that has placed an order
select count( distinct customer_key) as total_customers from gold.fact_sales

--Generate a report that shows all key metrics of business
SELECT 'Total Sales' AS measure_name,
       SUM(sales_amount) AS measure_value
FROM gold.fact_sales

UNION ALL

SELECT 'Total Quantity',
       SUM(quantity)
FROM gold.fact_sales

UNION ALL

SELECT 'Average Price',
       AVG(price)
FROM gold.fact_sales

UNION ALL

SELECT 'Total Nr. Orders',
       COUNT(DISTINCT order_number)
FROM gold.fact_sales

UNION ALL

SELECT 'Total Nr. Products',
       COUNT(product_name)
FROM gold.dim_product

UNION ALL

SELECT 'Total Nr. Customers',
       COUNT(customer_key)
FROM gold.dim_customers

-- Find total customers by countries
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category

SELECT category,
COUNT(product_key) AS total_products
from gold.dim_product
group by category
order by total_products DESC
-- What is the average costs in each category?
SELECT category,
AVG(cost) AS avg_costs
from gold.dim_product
group by category
order by avg_costs DESC
-- What is the total revenue generated for each category?
select 
p.category,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
LEFT JOIN gold.dim_product p
on p.product_key=f.product_key
group by p.category
order by total_revenue desc
-- Find total revenue is generated by each customer
select
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
on c.customer_key=f.customer_key
group by c.customer_key,
c.first_name,
c.last_name
order by total_revenue DESC
-- What is the distribution of sold items across countries?
select
c.country,
sum(quantity) as total_sold_items
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
on c.customer_key=f.customer_key
group by c.country 
order by total_sold_items DESC

--Which 5 products generates highest revenue?
select 
TOP 5
p.product_name,
sum(f.sales_amount) as total_revenue,
ROW_NUMBER() OVER(ORDER BY sum(f.sales_amount)) rank_products
from gold.fact_sales f
LEFT JOIN gold.dim_product p
on p.product_key=f.product_key
group by p.product_name
order by total_revenue desc
--What are the 5 worst-performing products in terms of sales?
select 
TOP 5
p.product_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
LEFT JOIN gold.dim_product p
on p.product_key=f.product_key
group by p.product_name
order by total_revenue 

-- Find Top 10 customers who generated highest revenue
select
TOP 10
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
on c.customer_key=f.customer_key
group by c.customer_key,
c.first_name,
c.last_name
order by total_revenue DESC

--The 3 customers with fewest orders placed

select
top 3
c.customer_key,
c.first_name,
c.last_name,
count(distinct order_number) as total_orders
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
on c.customer_key=f.customer_key
group by c.customer_key,
c.first_name,
c.last_name
order by total_orders 